repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ^ldm$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.16.0
    hooks:
      - id: markdownlint-cli2
