services:
  liferay:
    labels:
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie.name=LDM_STICKY"
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie.secure=true"
    volumes:
      - liferay-document-library:/opt/liferay/data/document_library
    environment:
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=true
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS=liferay

  liferay2:
    # liferay2 relies on the main liferay image being built/pulled
    image: liferay/portal:latest
    depends_on:
      liferay:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - liferay-net
    volumes:
      - liferay-document-library:/opt/liferay/data/document_library
      - ./osgi/configs:/opt/liferay/osgi/configs
    environment:
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=true
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS=liferay2
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:postgresql://db:5432/lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=lportal
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=test
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASE_C_LASS_UPPERCASE_N_AME=org.postgresql.Driver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.liferay-router.rule=HostRegexp(`{subdomain:.+}`)"
      - "traefik.http.services.liferay-router.loadbalancer.server.port=8080"
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie.name=LDM_STICKY"
      - "traefik.http.services.liferay-router.loadbalancer.sticky.cookie.secure=true"
      - "com.liferay.ldm.managed=true"

volumes:
  liferay-document-library: