cluster.link.enabled=true
cluster.link.channel.properties.control=osgi/configs/JGroups/tcp.xml
cluster.link.channel.properties.transport.0=osgi/configs/JGroups/tcp.xml
ehcache.cluster.link.replication.enabled=true