import os
import re
import sys
import platform
import subprocess
import shutil
from pathlib import Path
from datetime import datetime
from ldm_core.ui import UI
from ldm_core.constants import PROJECT_META_FILE, SCRIPT_DIR
from ldm_core.utils import get_actual_home


class BaseHandler:
    """Base mixin for LiferayManager containing shared core logic."""

    def __init__(self, args):
        self.args = args
        self.non_interactive = getattr(args, "non_interactive", False)
        self.verbose = getattr(args, "verbose", False)

    def _check_java_version(self, expected="21"):
        """Verifies the system Java version."""
        java_bin = shutil.which("java")
        if not java_bin:
            return False
        try:
            # Bandit: B603 (subprocess_without_shell_equals_true) is a general warning.
            res = subprocess.run(  # nosec B603
                [java_bin, "-version"], capture_output=True, text=True, check=True
            )
            output = res.stderr

            match = re.search(rf'version\s+"({expected}\.[^"]+)"', output)
            if match:
                if self.verbose:
                    UI.info(f"Verified system Java version: {match.group(1)}")
                return True
            UI.error(f"System Java version mismatch. Expected JDK {expected}.")
            print(f"{UI.WHITE}Actual output:{UI.COLOR_OFF}\n{output}")
            return False
        except Exception as e:
            UI.error(f"Failed to verify Java version: {e}")
            return False

    def _check_gradle_java_version(self, gradlew_path, expected="21"):
        """Verifies the JVM version used by Gradle."""
        try:
            if platform.system().lower() != "windows":
                # Bandit: B103 (chmod 0o755) is safe for gradlew as it needs to be executable.
                try:
                    os.chmod(gradlew_path, 0o755)  # nosec B103
                except Exception:
                    pass
            # Bandit: B603 (subprocess_without_shell_equals_true) is a general warning.
            res = subprocess.run(  # nosec B603
                [str(gradlew_path), "-v"], capture_output=True, text=True, check=True
            )
            output = res.stdout
            match = re.search(rf"JVM:\s+({expected}\.[^\s]+)", output)
            if match:
                if self.verbose:
                    UI.info(f"Verified Gradle JVM version: {match.group(1)}")
                return True
            UI.error(f"Gradle JVM version mismatch. Expected JDK {expected}.")
            print(f"{UI.WHITE}Actual output:{UI.COLOR_OFF}\n{output}")
            return False
        except Exception as e:
            UI.error(f"Failed to verify Gradle JVM version: {e}")
            return False

    def read_meta(self, path):
        """Reads project metadata from a flat file (key=value)."""
        meta = {}
        if not path.exists():
            return meta
        try:
            # Support both flat file (legacy/default) and JSON (future-proofing)
            content = path.read_text().strip()
            if content.startswith("{"):
                import json

                return json.loads(content)

            with open(path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        k, v = line.split("=", 1)
                        k, v = k.strip(), v.strip()
                        if v == "None":
                            v = None
                        elif v == "True":
                            v = True
                        elif v == "False":
                            v = False
                        meta[k] = v
        except Exception as e:
            if self.verbose:
                UI.warning(f"Could not read metadata at {path}: {e}")
        return meta

    def write_meta(self, path, meta):
        """Writes project metadata to a flat file (key=value)."""
        path = Path(path)
        try:
            tmp_path = path.with_suffix(".tmp")
            with open(tmp_path, "w") as f:
                f.write(f"# Generated by LDM ({datetime.now().isoformat()})\n")
                for k, v in sorted(meta.items()):
                    if v is not None:
                        f.write(f"{k}={v}\n")
            os.replace(tmp_path, path)
        except Exception as e:
            if self.verbose:
                UI.warning(f"Could not write metadata at {path}: {e}")

    def run_command(self, cmd, check=True, cwd=None, env=None, capture_output=True):
        from ldm_core.utils import run_command

        return run_command(
            cmd,
            check=check,
            cwd=cwd,
            env=env,
            capture_output=capture_output,
            verbose=self.verbose,
        )

    def require_compose(self, root_path, silent=False):
        """Verifies that a docker-compose.yml file exists in the project root."""
        if not root_path or not (root_path / "docker-compose.yml").exists():
            if not silent:
                UI.error(f"docker-compose.yml not found in {root_path}")
            return False
        return True

    def select_project_interactively(self, roots=None, heading="Select Project"):
        """Prompts the user to select a project from a list."""
        if self.non_interactive:
            return None

        project_roots = roots or self.find_dxp_roots()
        if not project_roots:
            return None

        UI.heading(heading)
        for i, r in enumerate(project_roots):
            print(f"[{i + 1}] {r['path'].name} [{UI.CYAN}{r['version']}{UI.COLOR_OFF}]")

        choice = UI.ask("Select project index, 's' to skip, or 'q' to quit", "1")
        if choice.lower() == "q":
            sys.exit(0)

        if choice.lower() == "s":
            return None

        try:
            idx = int(choice) - 1
            if 0 <= idx < len(project_roots):
                return project_roots[idx]
        except (ValueError, IndexError):
            pass
        return None

    def detect_project_path(self, project_id=None, for_init=False):
        """Resolves a project ID or path to a full filesystem path."""
        pid = project_id or getattr(self.args, "project", None)

        if not pid and Path.cwd().resolve() == Path.home().resolve():
            UI.warning(
                "You are running LDM from your Home directory. "
                "For better performance and to avoid noise, it is recommended to "
                "run LDM from a dedicated workspace folder (e.g. ~/ldm)."
            )

        if pid:
            p = Path(pid).expanduser().resolve()
            # Safety: exists() can raise PermissionError if the dir is 0700 root-owned
            try:
                if (p / PROJECT_META_FILE).exists() or (for_init and p.parent.exists()):
                    return p
            except PermissionError:
                # If we get permission denied, but the path exists, it's definitely the project
                if p.is_dir():
                    return p

            search_dirs = [
                Path.cwd(),
                Path.home() / "ldm",
                SCRIPT_DIR,
                Path("/Volumes/SanDisk/ldm"),
            ]
            custom_workspace = os.environ.get("LDM_WORKSPACE")
            if custom_workspace:
                search_dirs.append(Path(custom_workspace).expanduser().resolve())

            for s_dir in search_dirs:
                if not s_dir.exists():
                    continue
                p_test = s_dir / pid
                try:
                    if (p_test / PROJECT_META_FILE).exists() or (
                        for_init and s_dir.exists()
                    ):
                        return p_test
                except PermissionError:
                    if p_test.is_dir():
                        return p_test

            for s_dir in search_dirs:
                if not s_dir.exists():
                    continue
                try:
                    for item in s_dir.iterdir():
                        if item.is_dir() and not item.name.startswith("."):
                            meta_file = item / PROJECT_META_FILE
                            try:
                                if meta_file.exists():
                                    meta = self.read_meta(meta_file)
                                    if meta.get("project_name") == pid:
                                        return item.resolve()
                            except PermissionError:
                                continue
                except Exception:
                    continue

            if not for_init:
                UI.die(f"Project '{pid}' not found or missing {PROJECT_META_FILE}")

        cwd = Path.cwd()
        if (
            (cwd / "files" / "portal-ext.properties").exists()
            or (cwd / "deploy").exists()
            or (cwd / PROJECT_META_FILE).exists()
        ):
            return cwd

        selection = self.select_project_interactively()
        return selection["path"] if selection else None

    def find_dxp_roots(self, search_dir=None):
        """Discovers LDM projects in known locations."""
        if search_dir:
            return self._scan_dir(search_dir)

        # Aggregate from all known workspace locations
        all_roots = []
        seen_paths = set()
        search_dirs = [Path.cwd(), Path.home() / "ldm", Path("/Volumes/SanDisk/ldm")]

        custom_workspace = os.environ.get("LDM_WORKSPACE")
        if custom_workspace:
            search_dirs.append(Path(custom_workspace).expanduser().resolve())

        for s_dir in search_dirs:
            if not s_dir.exists():
                continue
            for r in self._scan_dir(s_dir):
                abs_p = r["path"].resolve()
                if abs_p not in seen_paths:
                    all_roots.append(r)
                    seen_paths.add(abs_p)

        return sorted(all_roots, key=lambda x: x["path"].name)

    def _scan_dir(self, d_path):
        """Internal helper to scan a single directory for projects."""
        roots = []
        d_path = Path(d_path)
        if not d_path.exists() or not d_path.is_dir():
            return roots

        is_ldm_root = d_path.name == "ldm"

        try:
            for item in d_path.iterdir():
                try:
                    if item.is_dir() and not item.name.startswith("."):
                        has_meta = (item / PROJECT_META_FILE).exists()
                        has_structure = (item / "files").exists() and (
                            item / "deploy"
                        ).exists()

                        # Logic:
                        # 1. If it has .meta, it's a project.
                        # 2. If it's in a known LDM root (like ~/ldm or /Volumes/SanDisk/ldm),
                        #    we allow structure-based discovery.
                        # 3. Otherwise (e.g. scanning Home directly), we REQUIRE .meta
                        #    to avoid picking up every folder in ~/
                        if has_meta or (is_ldm_root and has_structure):
                            meta = self.read_meta(item / PROJECT_META_FILE)
                            version = meta.get("tag") or "unknown"
                            roots.append({"path": item, "version": version})
                except PermissionError:
                    continue
        except PermissionError:
            pass
        return roots

    def parse_version(self, tag):
        """Parses a Liferay tag into a sortable tuple."""
        if not tag:
            return (0, 0, 0)
        parts = re.findall(r"\d+", str(tag))
        return tuple(map(int, parts))

    def get_common_dir(self, project_path=None):
        """Finds the 'common' directory by prioritizing CWD, Project Parent, then Binary Location."""
        common_path = Path.cwd() / "common"
        if common_path.exists():
            return common_path

        if project_path:
            p_parent_common = Path(project_path).resolve().parent / "common"
            if p_parent_common.exists():
                return p_parent_common

        exe_path = Path(sys.argv[0]).resolve()
        is_source = exe_path.suffix.lower() == ".py"

        if is_source:
            return SCRIPT_DIR / "common"
        else:
            return Path.cwd() / "common"

    def setup_paths(self, project_path):
        """Initializes a standard path dictionary for a project."""
        root = Path(project_path).resolve()
        common_path = self.get_common_dir(root)
        return {
            "root": root,
            "common": common_path,
            "data": root / "data",
            "deploy": root / "deploy",
            "files": root / "files",
            "configs": root / "osgi" / "configs",
            "marketplace": root / "osgi" / "marketplace",
            "state": root / "osgi" / "state",
            "modules": root / "osgi" / "modules",
            "backups": root / "snapshots",
            "cx": root / "osgi" / "client-extensions",
            "routes": root / "routes",
            "scripts": root / "scripts",
            "logs": root / "logs",
            "log4j": root / "osgi" / "log4j",
            "portal_log4j": root / "osgi" / "portal-log4j",
            "ce_dir": root / "client-extensions",
            "compose": root / "docker-compose.yml",
        }

    def verify_runtime_environment(self, paths):
        """Verifies volume mounts and synchronizes permissions across the project root."""
        root = paths["root"]
        system_type = platform.system().lower()

        if system_type in ["darwin", "linux"]:
            # Ensure the project root actually exists before we try to write to it
            try:
                if not root.exists():
                    root.mkdir(parents=True, exist_ok=True)
            except Exception as e:
                if self.verbose:
                    UI.warning(f"Could not ensure root directory exists: {e}")

            if self.verbose:
                UI.info("Synchronizing directory permissions via Docker...")

            import uuid

            token_val = f"LDM_VERIFY_{uuid.uuid4().hex[:8]}"
            token_file = root / ".ldm_mount_check"
            try:
                token_file.write_text(token_val)
            except (PermissionError, OSError) as e:
                if self.verbose:
                    UI.debug(f"Could not create mount-check token (ignoring): {e}")
                token_val = "SKIP"

            current_uid = os.getuid() if hasattr(os, "getuid") else 1000
            current_gid = os.getgid() if hasattr(os, "getgid") else 1000

            try:
                # HARDENING: Mount the parent directory to ensure we can definitely
                # fix permissions and ownership for the project root directory itself.
                # Mount propagation can sometimes block chown on the mount point itself.
                parent = root.parent.resolve()
                rel_root = root.name

                # Aggressive sub-directory creation and reclamation
                # We specifically ensure the root directory (/workspace/{rel_root}) is chowned/chmodded
                docker_cmd = (
                    f"mkdir -p /workspace/{rel_root}/data /workspace/{rel_root}/deploy /workspace/{rel_root}/files "
                    f"/workspace/{rel_root}/osgi/state /workspace/{rel_root}/osgi/configs /workspace/{rel_root}/osgi/modules "
                    f"/workspace/{rel_root}/routes /workspace/{rel_root}/snapshots 2>/dev/null || true; "
                    f"chown -R {current_uid}:{current_gid} /workspace/{rel_root} 2>/dev/null || true; "
                    f"chmod -R 777 /workspace/{rel_root} 2>/dev/null || true; "
                    f"chmod 777 /workspace/{rel_root} 2>/dev/null || true; "
                )

                if token_val != "SKIP":
                    docker_cmd = (
                        f'if [ "$(cat /workspace/{rel_root}/.ldm_mount_check 2>/dev/null)" = "{token_val}" ]; then '
                        f"{docker_cmd}"
                        f"if touch /workspace/{rel_root}/.ldm_write_test 2>/dev/null; then echo 'OK'; else echo 'NO_WRITE'; fi; "
                        f"else echo 'FAIL'; fi"
                    )
                else:
                    # In SKIP mode, we just do our best and assume success if the command finishes
                    docker_cmd = f"{docker_cmd} echo 'OK'"

                verify_res = self.run_command(
                    [
                        "docker",
                        "run",
                        "--rm",
                        "-v",
                        f"{parent.as_posix()}:/workspace",
                        "alpine",
                        "sh",
                        "-c",
                        docker_cmd,
                    ]
                )

                if "OK" not in (verify_res or ""):
                    if "NO_WRITE" in (verify_res or ""):
                        UI.error("\n❌ FATAL: VOLUME MOUNT IS READ-ONLY")
                        UI.info(
                            f"{UI.BYELLOW}Reason:{UI.COLOR_OFF} Docker can see the files, but the 'liferay' user cannot write to: {root}"
                        )
                    else:
                        UI.error("\n❌ FATAL: VOLUME MOUNTING IS BROKEN")
                        UI.info(
                            f"{UI.BYELLOW}Reason:{UI.COLOR_OFF} Docker cannot see the files in: {root}"
                        )

                    if system_type == "darwin":
                        actual_home = Path.home()
                        try:
                            from ldm_core.utils import get_actual_home

                            actual_home = get_actual_home()
                        except ImportError:
                            pass

                        cert_dir = actual_home / "liferay-docker-certs"
                        mount_hint = self.get_colima_mount_flags([root, cert_dir])

                        UI.info(f"\n{UI.CYAN}To fix this, run:{UI.COLOR_OFF}")
                        UI.info("colima stop")
                        UI.info(
                            f"colima start {mount_hint} --vm-type=vz --mount-type=virtiofs"
                        )

                    sys.exit(1)

                if system_type == "darwin" and self.verbose:
                    UI.success("Volume mounts verified and permissions synchronized.")
            except Exception as e:
                if self.verbose:
                    UI.warning(f"Could not verify mounts automatically: {e}")
            finally:
                try:
                    if token_file.exists():
                        token_file.unlink()
                    write_test = root / ".ldm_write_test"
                    if write_test.exists():
                        write_test.unlink()
                except Exception:
                    pass
        else:
            pass

        for p_key in [
            "data",
            "deploy",
            "files",
            "state",
            "cx",
            "configs",
            "modules",
            "backups",
        ]:
            if p_key in paths:
                try:
                    paths[p_key].mkdir(parents=True, exist_ok=True)
                except Exception as e:
                    if self.verbose:
                        UI.warning(f"Could not create directory {paths[p_key]}: {e}")

        pe_file = paths["files"] / "portal-ext.properties"
        if pe_file.exists() and pe_file.is_dir():
            UI.warning(f"Removing ghost directory at {pe_file}")
            self.safe_rmtree(pe_file)

        if not pe_file.exists():
            try:
                pe_file.touch()
            except Exception:
                pass

    def check_docker(self):
        """Verifies Docker accessibility."""
        try:
            docker_bin = shutil.which("docker")
            if not docker_bin:
                return False

            res = subprocess.run(
                [docker_bin, "version", "--format", "{{.Server.Version}}"],
                capture_output=True,
                text=True,
                check=False,
            )
            if res.returncode == 0:
                return True

            if hasattr(os, "getuid") and os.getuid() == 0:
                UI.error("\n❌ FATAL: RUNNING AS ROOT/SUDO IS PROHIBITED")
                if platform.system().lower() == "linux":
                    UI.info(
                        f"If you are using sudo because of Docker permissions, please run:\n"
                        f"{UI.CYAN}sudo usermod -aG docker $USER{UI.COLOR_OFF} and restart your terminal session.\n"
                    )
                sys.exit(1)

            return False
        except Exception:
            return False

    def migrate_layout(self, paths):
        """Ensures modern project directory structure and permissions."""
        essential_paths = [
            "data",
            "deploy",
            "state",
            "marketplace",
            "files",
            "configs",
            "modules",
            "cx",
            "scripts",
            "routes",
            "logs",
            "log4j",
            "portal_log4j",
        ]
        for key in essential_paths:
            if key in paths:
                try:
                    paths[key].mkdir(parents=True, exist_ok=True)
                except Exception as e:
                    if self.verbose:
                        UI.warning(
                            f"Could not ensure directory exists {paths[key]}: {e}"
                        )

        routes_base = paths["root"] / "routes" / "default" / "dxp"
        try:
            routes_base.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            if self.verbose:
                UI.warning(f"Could not ensure routes directory exists: {e}")

        if platform.system().lower() != "windows":
            try:
                os.chmod(str(paths["root"]), 0o777)  # nosec B103
                for key in essential_paths:
                    if key in paths and paths[key].exists():
                        os.chmod(str(paths[key]), 0o777)  # nosec B103
            except Exception:
                pass

    def get_resolved_ip(self, host_name):
        """Resolves a hostname to its IP address."""
        if not host_name or host_name == "localhost":
            return "127.0.0.1"
        try:
            import socket

            return socket.gethostbyname(host_name)
        except socket.gaierror:
            return None

    def check_hostname(self, host_name):
        """Verifies that the hostname resolves to the local machine, helping the user fix it if not."""
        if host_name == "localhost":
            return True

        resolved_ip = self.get_resolved_ip(host_name)
        if resolved_ip:
            return True

        UI.error(f"Hostname '{host_name}' does not resolve to any IP address.")
        UI.info(
            f"Please add it to your local hosts file or run '{UI.WHITE}ldm doctor --fix-hosts{UI.COLOR_OFF}'."
        )
        return False

    def validate_project_dns(self, project_id):
        """Verifies that the project's hostname and all active client extensions resolve correctly."""
        root = self.detect_project_path(project_id)
        if not root:
            return False, []

        paths = self.setup_paths(root)
        meta = self.read_meta(root / PROJECT_META_FILE)
        host_name = meta.get("host_name", "localhost")
        if host_name == "localhost":
            return True, []

        unresolved = []
        if not self.get_resolved_ip(host_name):
            unresolved.append(host_name)

        if paths["cx"].exists():
            from ldm_core.handlers.workspace import WorkspaceHandler

            handler = WorkspaceHandler()
            handler.args = self.args
            extensions = handler.scan_client_extensions(
                paths["root"], paths["cx"], paths["ce_dir"]
            )
            for ext in extensions:
                if ext.get("deploy") and ext.get("has_load_balancer"):
                    ext_host = f"{ext['id']}.{host_name}"
                    if not self.get_resolved_ip(ext_host):
                        unresolved.append(ext_host)

        return len(unresolved) == 0, unresolved

    def safe_rmtree(self, path):
        """Securely deletes a directory tree, handling potential Docker/Root permission issues."""
        if not path or not path.exists():
            return

        try:
            shutil.rmtree(path)
        except (PermissionError, OSError):
            parent = path.parent.resolve()

            # Harden for Colima/Lima:
            # We use standard /var/run/docker.sock to avoid 'operation not supported' errors
            # when mounting host paths into cleanup containers.
            self.run_command(
                [
                    "docker",
                    "run",
                    "--rm",
                    "-v",
                    f"{parent.as_posix()}:/parent",
                    "alpine",
                    "sh",
                    "-c",
                    f"chmod -R 777 /parent/{path.name} 2>/dev/null || true; rm -rf /parent/{path.name} 2>/dev/null || true",
                ],
                check=False,
            )

            # Fallback check
            if path.exists():
                try:
                    shutil.rmtree(path)
                except Exception:
                    pass

    def get_colima_mount_flags(self, paths):
        """Generates the necessary --mount flags for Colima based on project paths."""
        mounts = set()
        real_user = os.environ.get("USER") or os.environ.get("LOGNAME")

        for p in paths:
            abs_path = Path(p).resolve()
            parts = abs_path.parts

            if len(parts) >= 3 and parts[1] in ["Users", "Volumes"]:
                mount_point = os.path.join(parts[0], parts[1], parts[2])
                if parts[1] == "Users" and real_user and parts[2] == real_user:
                    mount_point = os.path.join(parts[0], parts[1], "$(whoami)")
            elif len(parts) >= 2:
                mount_point = os.path.join(parts[0], parts[1])
            else:
                mount_point = parts[0]

            mounts.add(f"--mount {mount_point}:w")

        return " ".join(sorted(list(mounts)))

    def get_resource_path(self, filename):
        """Resiliently locates internal resource files (supports source vs bundled)."""
        # 1. Check bundled package structure (site-packages/ldm_core/resources)
        path = SCRIPT_DIR / "ldm_core" / "resources" / filename
        if path.exists():
            return path

        # 2. Check source development structure (root/resources)
        path = SCRIPT_DIR / "resources" / filename
        if path.exists():
            return path

        return None

    def _refresh_man_symlink(self):
        """Ensures a stable symlink for the man page exists in ~/.ldm/man/man1/."""
        if platform.system().lower() == "windows":
            return

        try:
            man_source = self.get_resource_path("ldm.1")
            if not man_source:
                return

            home = get_actual_home()
            man_dir = home / ".ldm" / "man" / "man1"
            man_dir.mkdir(parents=True, exist_ok=True)
            man_link = man_dir / "ldm.1"

            if man_link.is_symlink() or man_link.exists():
                man_link.unlink()

            man_link.symlink_to(man_source)
        except Exception:
            # Silent fail for symlink refresh
            pass

    def cmd_completion(self, target_shell=None):
        """Displays instructions or outputs shellcode for enabling completion."""
        # Detect active shell if not provided
        active_shell = os.environ.get("SHELL", "").split("/")[-1].lower()
        if active_shell.endswith(".exe"):
            active_shell = active_shell[:-4]

        # Normalize pwsh to powershell for internal logic
        if active_shell == "pwsh":
            active_shell = "powershell"

        # Refresh man symlink so 'man ldm' setup is always ready
        self._refresh_man_symlink()

        # If target_shell is specifically requested via CLI (e.g. 'ldm completion zsh')
        # we MUST only output shellcode to stdout to avoid breaking 'eval'.
        if target_shell:
            target_shell = target_shell.lower()
            try:
                import argcomplete

                if target_shell == "zsh":
                    # We use the internal argcomplete shellcode generator
                    code = argcomplete.shellcode(["ldm"], shell="zsh")  # nosec B604
                    # Zsh requires compinit to support the 'compdef' command used by argcomplete
                    print("# LDM Zsh Completion Initialization")
                    print(
                        "(( $+functions[compdef] )) || { autoload -U compinit && compinit }"
                    )
                    print(code)
                    return
                elif target_shell == "bash":
                    print(
                        argcomplete.shellcode(["ldm"], shell="bash")  # nosec B604
                    )
                    return
                elif target_shell == "fish":
                    print(
                        argcomplete.shellcode(["ldm"], shell="fish")  # nosec B604
                    )
                    return
                elif target_shell == "powershell":
                    # PowerShell doesn't have native argcomplete support, so we provide a bridge script
                    print("# LDM PowerShell Completion Bridge")
                    print(
                        "if (-not (Get-Command ldm -ErrorAction SilentlyContinue)) { return }"
                    )
                    print("$scriptblock = {")
                    print(
                        "    param($commandName, $wordToComplete, $cursorPosition, $commandAst, $fakeBoundParameters)"
                    )
                    print("    $env:COMP_LINE = $commandAst.ToString()")
                    print("    $env:COMP_POINT = $cursorPosition")
                    print("    $env:_ARGCOMPLETE = 1")
                    print("    $results = & ldm 2>$null")
                    print("    $results | ForEach-Object {")
                    print(
                        "        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)"
                    )
                    print("    }")
                    print(
                        "    Remove-Item Env:COMP_LINE, Env:COMP_POINT, Env:_ARGCOMPLETE"
                    )
                    print("}")
                    print(
                        "Register-ArgumentCompleter -Native -CommandName ldm -ScriptBlock $scriptblock"
                    )
                    return
            except Exception as e:
                # If generation fails, we print the error to stderr so eval ignores it
                print(f"Error generating completion: {e}", file=sys.stderr)
                return

        UI.heading("LDM Shell Completion")
        shell = active_shell
        if shell not in ["bash", "zsh", "fish", "powershell"]:
            UI.info(
                f"Completion is currently optimized for bash, zsh, fish, and powershell. (Found: {shell})"
            )
            return

        UI.info(
            f"To enable tab-completion for {UI.BYELLOW}{shell}{UI.COLOR_OFF}, add this to your startup profile:"
        )

        if shell == "zsh":
            print('\n    eval "$(ldm completion zsh)"\n')
            profile = ".zshrc"
        elif shell == "bash":
            print('\n    eval "$(ldm completion bash)"\n')
            profile = ".bashrc"
        elif shell == "fish":
            print("\n    ldm completion fish | source\n")
            profile = "config.fish"
        elif shell == "powershell":
            print("\n    ldm completion powershell | Out-String | Invoke-Expression\n")
            profile = "Microsoft.PowerShell_profile.ps1"

        UI.info(
            f"To support native {UI.BOLD}man ldm{UI.COLOR_OFF}, add this to the same file:"
        )
        print('\n    export MANPATH="$MANPATH:$HOME/.ldm/man"\n')

        UI.info(
            f"You may need to restart your terminal or source your profile ({UI.CYAN}~/{profile}{UI.COLOR_OFF})"
        )
        print("for the changes to take effect.")

    def cmd_man(self):
        """Displays the ldm manual page."""
        self._refresh_man_symlink()
        man_path = self.get_resource_path("ldm.1")
        if not man_path:
            UI.die("Manual page 'ldm.1' not found in resources.")

        # On macOS/Linux, we can use 'man -l' to view a local file
        # Fallback to 'less' if 'man' is not found or fails
        try:
            import subprocess

            if platform.system().lower() != "windows":
                # Check if man supports -l (macOS and most Linux)
                res = subprocess.run(
                    ["man", "--help"], capture_output=True, text=True, check=False
                )
                if "-l" in res.stdout or "-l" in res.stderr:
                    subprocess.run(["man", "-l", str(man_path)])
                else:
                    # Fallback to less with roff processing if possible, or raw text
                    # We can use mandoc or groff if available
                    if shutil.which("mandoc"):
                        subprocess.run(
                            f"mandoc -Tutf8 {man_path} | less -R",
                            shell=True,  # nosec B602 B604
                        )
                    elif shutil.which("groff"):
                        subprocess.run(
                            f"groff -man -Tascii {man_path} | less -R",
                            shell=True,  # nosec B602 B604
                        )
                    else:
                        subprocess.run(["less", str(man_path)])
            else:
                # Windows fallback to notepad or similar
                subprocess.run(["notepad", str(man_path)])
        except Exception as e:
            UI.error(f"Failed to display manual: {e}")
            UI.info(f"You can view the raw manual file at: {man_path}")
