#!/usr/bin/env python3
import re
from pathlib import Path

# --- Configuration ---
SOURCE_FILE = Path("terminal-colors.txt")
PY_DEST = Path("ldm_core/ui_colors.py")
SH_DEST = Path("scripts/colors.sh")


def sync_colors():
    """Generates Python and Shell color definitions from terminal-colors.txt."""
    print(f"Syncing colors: {SOURCE_FILE} -> {PY_DEST}, {SH_DEST}")

    if not SOURCE_FILE.exists():
        print(f"Error: {SOURCE_FILE} not found.")
        return

    content = SOURCE_FILE.read_text()

    # Extract definitions: Name='Value'
    pattern = re.compile(r"^([A-Za-z_]+)='([^']+)'", re.MULTILINE)
    matches = pattern.findall(content)

    if not matches:
        print("Error: No color definitions found in terminal-colors.txt.")
        return

    # 1. Generate Python
    py_lines = [
        "# --- Generated by scripts/sync_colors.py ---",
        "class UIColors:",
    ]
    for name, value in matches:
        # Standardize to uppercase for Python class constants
        py_lines.append(f'    {name.upper()} = "{value}"')

    PY_DEST.write_text("\n".join(py_lines) + "\n")
    print(f"  + Generated {PY_DEST}")

    # 2. Generate Shell
    sh_lines = [
        "#!/bin/sh",
        "# shellcheck disable=SC2034",
        "# --- Generated by scripts/sync_colors.py ---",
    ]
    for name, value in matches:
        # Standardize to uppercase with UI_ prefix for Shell
        sh_lines.append(f"UI_{name.upper()}='{value}'")

    SH_DEST.write_text("\n".join(sh_lines) + "\n")
    print(f"  + Generated {SH_DEST}")

    print("Color sync complete.")


if __name__ == "__main__":
    sync_colors()
