include-and-override=portal-developer.properties
cache.filter.include.user.agent=false
com.liferay.portal.servlet.filters.cache.CacheFilter=false
passwords.default.policy.change.required=false
session.timeout=120
setup.wizard.enabled=false
terms.of.use.required=false
users.reminder.queries.enabled=false
company.login.prepopulate.domain=false
company.security.strangers.with.mx=false
company.security.auto.login=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.send.password.reset.link=false
company.security.update.password.required=false
layout.user.private.layouts.enabled=false
layout.user.private.layouts.auto.create=false
layout.user.public.layouts.enabled=false
layout.user.public.layouts.auto.create=false
field.enable.com.liferay.portal.kernel.model.Contact.male=false
field.enable.com.liferay.portal.kernel.model.Contact.birthday=false
session.timeout.auto.extend=true
session.timeout.auto.extend.offset=10
feature.flag.ui.visible[dev]=true
dl.file.entry.preview.image.mime.types=image/bmp,\
image/gif,\
image/jpeg,\
image/pjpeg,\
image/png,\
image/tiff,\
image/x-citrix-jpeg,\
image/x-citrix-png,\
image/x-ms-bmp,\
image/x-png,\
image/x-tiff,\
image/webp,\
image/avif

jdbc.default.enabled=true
jdbc.default.driverClassName=org.mariadb.jdbc.Driver
jdbc.default.url=jdbc:mariadb://db:3306/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&prepStmtCacheSize=1000&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&useLocalTransactionState=true&permitMysqlScheme=true
jdbc.default.username=lportal
jdbc.default.password=test
hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
